name    'kickstandproject-zuul'
version '0.0.1'
author 'kickstandproject'
license 'Apache 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'https://github.com/kickstandproject/kickstandproject-zuul'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
