kickstand-dev:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - kickstandproject/fastdraw
      - kickstandproject/payload
      - kickstandproject/python-payloadclient
      - kickstandproject/python-ripcordclient
      - kickstandproject/ripcord
      - kickstandproject/wildcard
      - kickstandproject-dev/grunt
    branches:
      - master

kickstand-infra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - kickstandproject/kickstandproject-ci-puppet
      - kickstandproject-infra/kickstandproject-apt
    branches:
      - master
